name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID_DEV }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID_DEV }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_DEV }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_DEV }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_DEV }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_DEV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enhanced Debug
        run: |
          echo "=== Secret Existence Check ==="
          echo "Project ID exists: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID_DEV != '' }}"
          echo "API Key exists: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_DEV != '' }}"
          echo "Auth Domain exists: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_DEV != '' }}"
          
          echo "=== Environment Variable Lengths ==="
          echo "Project ID length: ${#NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
          echo "API Key length: ${#NEXT_PUBLIC_FIREBASE_API_KEY}"
          echo "Auth Domain: $NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
          
          echo "=== Context Info ==="
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: false
          spec: cypress/e2e/signup.cy.ts
