name: Deploy to Firebase App Hosting on Production Push
on:
  push:
    branches:
      - production
env:
  PROJECT_ID: joaquin-q0wvv
  FIREBASE_PROJECT_ID: joaquin-q0wvv
  
jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # This permission is essential for Workload Identity Federation!
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: auth
        name: Authenticate to Google Cloud (Workload Identity Federation)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/371246421587/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-apphosting@joaquin-q0wvv.iam.gserviceaccount.com'
          create_credentials_file: true # This creates the WIF credentials file and sets GOOGLE_APPLICATION_CREDENTIALS
      - name: Write service account key to file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $GITHUB_WORKSPACE/firebase-key.json
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase-key.json" >> $GITHUB_ENV
      - name: Debug authentication status
        run: |
          echo "Authentication completed"
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Credentials file exists"
            echo "File size: $(stat -c%s "$GOOGLE_APPLICATION_CREDENTIALS") bytes"
          else
            echo "Credentials file does not exist"
          fi
          gcloud auth list
      - name: Deploy to Firebase App Hosting
        run: firebase apphosting:rollouts:create joaquin-prod --project joaquin-q0wvv --location europe-west4
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
