# This workflow triggers a new rollout for your Firebase App Hosting backend
# when changes are pushed to the 'production' branch.

name: Deploy to Firebase App Hosting on Production Push

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: 'FirebaseExtended/setup-gcloud-auth@v1'
        with:
          credentials_base64: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOAQUIN_PROD }}'
          project_id: 'joaquin-q0wvv'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Trigger App Hosting Rollout
        run: firebase apphosting:rollouts:create joaquin-prod --project joaquin-q0wvv --git-branch production --git-commit ${{ github.sha }}
