
name: Deploy to Firebase App Hosting on Production Push

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    env:
      # (optional) make your NEXT_PUBLIC_… secrets available here too
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOAQUIN_PROD }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: joaquin-q0wvv
          install_components: ['beta']        # needed for apphosting
          export_default_credentials: true   # sets GOOGLE_APPLICATION_CREDENTIALS

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Trigger App Hosting Rollout
        run: |
          firebase apphosting:rollouts:create \
            joaquin-prod \
            --project=joaquin-q0wvv \
            --git-branch=${{ github.ref_name }} \
            --git-commit=${{ github.sha }}
