name: Deploy to Firebase App Hosting on Production Push

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # This permission is essential for Workload Identity Federation!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud (Workload Identity Federation)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/371246421587/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-apphosting@joaquin-q0wvv.iam.gserviceaccount.com'
          create_credentials_file: true # This creates the file and sets GOOGLE_APPLICATION_CREDENTIALS

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # --- NEW/REVISED STEP: Generate Firebase Access Token ---
      # This step gets a short-lived access token using gcloud,
      # which correctly picks up the WIF credentials.
      - name: Generate Firebase Access Token
        id: generate_token # Add an ID to this step to access its outputs
        run: |
          # Use gcloud to print an access token. This command will use the ADC set up by the 'auth' step.
          # We capture its output into a variable that can be accessed by later steps.
          echo "ACCESS_TOKEN=$(gcloud auth print-access-token)" >> "$GITHUB_OUTPUT"
        env:
          # Ensure gcloud uses the specific project for authentication context
          CLOUDSDK_CORE_PROJECT: joaquin-q0wvv

      - name: Trigger App Hosting Rollout
        # Pass the generated ACCESS_TOKEN as an environment variable to the Firebase CLI.
        # This is the most reliable way to authenticate firebase-tools in CI/CD.
        env:
          FIREBASE_TOKEN: ${{ steps.generate_token.outputs.ACCESS_TOKEN }}
        run: |
          firebase apphosting:rollouts:create joaquin-prod \
            --project=joaquin-q0wvv \
            --git-branch=${{ github.ref_name }} \
            --git-commit=${{ github.sha }}
