name: Deploy to Firebase App Hosting on Production Push
on:
  push:
    branches:
      - production
env:
  PROJECT_ID: joaquin-q0wvv
  FIREBASE_PROJECT_ID: joaquin-q0wvv
  
jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Write service account key to file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $GITHUB_WORKSPACE/firebase-key.json
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase-key.json" >> $GITHUB_ENV
      - name: Debug authentication status
        run: |
          echo "Authentication completed"
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Credentials file exists"
            echo "File size: $(stat -c%s "$GOOGLE_APPLICATION_CREDENTIALS") bytes"
          else
            echo "Credentials file not found!"
          fi
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          export PATH="$PATH:$HOME/.local/bin"
      - name: Activate service account with gcloud
        run: |
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
          gcloud config set project "$PROJECT_ID"
      - name: Deploy to Firebase App Hosting
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          firebase apphosting:backends:deploy --project=$PROJECT_ID
