name: Deploy to Firebase App Hosting on Production Push
on:
  push:
    branches:
      - production
jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # This permission is essential for Workload Identity Federation!
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: auth
        name: Authenticate to Google Cloud (Workload Identity Federation)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/371246421587/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-apphosting@joaquin-q0wvv.iam.gserviceaccount.com'
          create_credentials_file: true # This creates the WIF credentials file and sets GOOGLE_APPLICATION_CREDENTIALS
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate Firebase CLI with ADC
        run: |
          # The google-github-actions/auth action has set up Application Default Credentials (ADC)
          # Firebase CLI will automatically use these credentials when GOOGLE_APPLICATION_CREDENTIALS is set
          # We just need to verify the authentication is working
          firebase --version
          firebase projects:list
          echo "Firebase CLI authenticated successfully using Application Default Credentials"
      - name: Trigger App Hosting Rollout
        run: |
          firebase apphosting:rollouts:create joaquin-prod \
            --project joaquin-q0wvv \
            --git-branch=${{ github.ref_name }} \
            --git-commit=${{ github.sha }}
