# This workflow triggers a new rollout for your Firebase App Hosting backend
# when changes are pushed to the 'production' branch.

name: Deploy to Firebase App Hosting on Production Push

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Build project
        run: npm run build

      - name: Authenticate with Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOAQUIN_PROD }}'

      - name: Set up gcloud for Firebase
        run: |
          gcloud auth activate-service-account --key-file=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          gcloud config set project joaquin-q0wvv

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Trigger App Hosting Rollout
        run: firebase apphosting:rollouts:create joaquin-prod --project joaquin-q0wvv --git-branch production --git-commit ${{ github.sha }}
