      # ... (previous steps) ...

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI using direct Access Token
        run: |
          # The google-github-actions/auth step provides its token as "auth_token", not "access_token".
          firebase login --token "${{ steps.auth.outputs.auth_token }}" --project=joaquin-q0wvv
      # --- END CRITICAL REVISION ---

      - name: Trigger App Hosting Rollout
        # Now, the Firebase CLI should be authenticated and ready to deploy!
        run: |
          firebase apphosting:rollouts:create joaquin-prod \
            --project=joaquin-q0wvv \
            --git-branch=${{ github.ref_name }} \
            --git-commit=${{ github.sha }}
